"""add new table room type 

Revision ID: 07e687e9cc98
Revises: 734f0808e23d
Create Date: 2026-08-11 11:21:05.665282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e687e9cc98'
down_revision: Union[str, Sequence[str], None] = '734f0808e23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_room_type_id'), table_name='properties')
    op.drop_constraint(op.f('properties_room_type_id_fkey'), 'properties', type_='foreignkey')
    op.drop_column('properties', 'room_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('room_type_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('properties_room_type_id_fkey'), 'properties', 'room_types', ['room_type_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_properties_room_type_id'), 'properties', ['room_type_id'], unique=False)
    # ### end Alembic commands ###
