"""agreement template model add

Revision ID: 111c3b6a137c
Revises: g1a2b3c4d5e6
Create Date: 2026-09-22 08:38:39.737936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111c3b6a137c'
down_revision: Union[str, Sequence[str], None] = 'g1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('rich_text', 'pdf_upload', name='agreementtemplatetype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', 'archived', name='agreementtemplatestatus'), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('pdf_file_key', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_templates_created_by'), 'agreement_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_agreement_templates_is_default'), 'agreement_templates', ['is_default'], unique=False)
    op.create_index(op.f('ix_agreement_templates_public_id'), 'agreement_templates', ['public_id'], unique=True)
    op.create_index(op.f('ix_agreement_templates_status'), 'agreement_templates', ['status'], unique=False)
    op.create_index(op.f('ix_agreement_templates_template_type'), 'agreement_templates', ['template_type'], unique=False)
    op.drop_index(op.f('uq_amenity_global_name'), table_name='amenities', postgresql_where='(vendor_id IS NULL)')
    op.alter_column('cities', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('countries', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('uq_facility_global_name'), table_name='facilities', postgresql_where='(vendor_id IS NULL)')
    op.alter_column('locations', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('property_room_type_prices', 'occupancy',
               existing_type=sa.INTEGER(),
               comment='Number of guests this price tier applies to (1, 2, 3, 4, etc.)',
               existing_nullable=False)
    op.alter_column('property_room_type_prices', 'price_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Standard nightly price for this occupancy count',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_type_prices', 'sale_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Discounted nightly price for this occupancy count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_types', 'price_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Base price per night for this room type',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_types', 'sale_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Sale price per night for this room type',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('uq_room_type_global_name'), table_name='room_types', postgresql_where='(vendor_id IS NULL)')
    op.add_column('vendor_agreements', sa.Column('template_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_vendor_agreements_template_id'), 'vendor_agreements', ['template_id'], unique=False)
    op.create_foreign_key(None, 'vendor_agreements', 'agreement_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_agreements', type_='foreignkey')
    op.drop_index(op.f('ix_vendor_agreements_template_id'), table_name='vendor_agreements')
    op.drop_column('vendor_agreements', 'template_id')
    op.create_index(op.f('uq_room_type_global_name'), 'room_types', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(vendor_id IS NULL)')
    op.alter_column('property_room_types', 'sale_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Sale price per night for this room type',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_types', 'price_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Base price per night for this room type',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_type_prices', 'sale_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Discounted nightly price for this occupancy count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_type_prices', 'price_per_night',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Standard nightly price for this occupancy count',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('property_room_type_prices', 'occupancy',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of guests this price tier applies to (1, 2, 3, 4, etc.)',
               existing_nullable=False)
    op.alter_column('locations', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('uq_facility_global_name'), 'facilities', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(vendor_id IS NULL)')
    op.alter_column('countries', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cities', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('uq_amenity_global_name'), 'amenities', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(vendor_id IS NULL)')
    op.drop_index(op.f('ix_agreement_templates_template_type'), table_name='agreement_templates')
    op.drop_index(op.f('ix_agreement_templates_status'), table_name='agreement_templates')
    op.drop_index(op.f('ix_agreement_templates_public_id'), table_name='agreement_templates')
    op.drop_index(op.f('ix_agreement_templates_is_default'), table_name='agreement_templates')
    op.drop_index(op.f('ix_agreement_templates_created_by'), table_name='agreement_templates')
    op.drop_table('agreement_templates')
    # ### end Alembic commands ###
