"""add new tables for payouts

Revision ID: 1c1eb3bb7ae2
Revises: b1c2d3e4f5a6
Create Date: 2026-09-01 02:26:51.357344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1eb3bb7ae2'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_bank_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.Enum('BANK_ACCOUNT', 'VPA', name='bankaccounttype'), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_fund_account_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bank_accounts_account_number'), 'vendor_bank_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_account_type'), 'vendor_bank_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_ifsc_code'), 'vendor_bank_accounts', ['ifsc_code'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_public_id'), 'vendor_bank_accounts', ['public_id'], unique=True)
    op.create_index(op.f('ix_vendor_bank_accounts_razorpay_contact_id'), 'vendor_bank_accounts', ['razorpay_contact_id'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_razorpay_fund_account_id'), 'vendor_bank_accounts', ['razorpay_fund_account_id'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_upi_id'), 'vendor_bank_accounts', ['upi_id'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_vendor_id'), 'vendor_bank_accounts', ['vendor_id'], unique=False)
    op.drop_constraint(op.f('uq_bookings_invoice_number'), 'bookings', type_='unique')
    op.create_index(op.f('ix_host_request_messages_sender_id'), 'host_request_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_host_requests_converted_user_id'), 'host_requests', ['converted_user_id'], unique=False)
    op.create_index(op.f('ix_host_requests_reviewed_by'), 'host_requests', ['reviewed_by'], unique=False)
    op.add_column('payouts', sa.Column('bank_account_id', sa.BigInteger(), nullable=True))
    op.add_column('payouts', sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payouts', sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payouts', sa.Column('mode', sa.String(length=20), nullable=True))
    op.add_column('payouts', sa.Column('razorpay_payout_id', sa.String(length=255), nullable=True))
    op.add_column('payouts', sa.Column('razorpay_fund_account_id', sa.String(length=255), nullable=True))
    op.add_column('payouts', sa.Column('utr', sa.String(length=100), nullable=True))
    op.add_column('payouts', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('payouts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('payouts', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_payouts_bank_account_id'), 'payouts', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_payouts_razorpay_payout_id'), 'payouts', ['razorpay_payout_id'], unique=True)
    op.create_foreign_key(None, 'payouts', 'vendor_bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payouts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.drop_index(op.f('ix_payouts_razorpay_payout_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_bank_account_id'), table_name='payouts')
    op.drop_column('payouts', 'created_by')
    op.drop_column('payouts', 'notes')
    op.drop_column('payouts', 'failure_reason')
    op.drop_column('payouts', 'utr')
    op.drop_column('payouts', 'razorpay_fund_account_id')
    op.drop_column('payouts', 'razorpay_payout_id')
    op.drop_column('payouts', 'mode')
    op.drop_column('payouts', 'commission_amount')
    op.drop_column('payouts', 'gross_amount')
    op.drop_column('payouts', 'bank_account_id')
    op.drop_index(op.f('ix_host_requests_reviewed_by'), table_name='host_requests')
    op.drop_index(op.f('ix_host_requests_converted_user_id'), table_name='host_requests')
    op.drop_index(op.f('ix_host_request_messages_sender_id'), table_name='host_request_messages')
    op.create_unique_constraint(op.f('uq_bookings_invoice_number'), 'bookings', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_vendor_bank_accounts_vendor_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_upi_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_razorpay_fund_account_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_razorpay_contact_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_public_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_ifsc_code'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_account_type'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_account_number'), table_name='vendor_bank_accounts')
    op.drop_table('vendor_bank_accounts')
    # ### end Alembic commands ###
