"""add new tables for payouts

Revision ID: 24071b64e5fc
Revises: b2c3d4e5f6a7
Create Date: 2026-09-06 03:08:19.220065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24071b64e5fc'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_razorpay_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_contact_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', name='uq_vendor_razorpay_contacts_vendor_id')
    )
    op.create_index(op.f('ix_vendor_razorpay_contacts_public_id'), 'vendor_razorpay_contacts', ['public_id'], unique=True)
    op.create_index(op.f('ix_vendor_razorpay_contacts_razorpay_contact_id'), 'vendor_razorpay_contacts', ['razorpay_contact_id'], unique=True)
    op.create_index(op.f('ix_vendor_razorpay_contacts_vendor_id'), 'vendor_razorpay_contacts', ['vendor_id'], unique=False)
    op.create_table('vendor_razorpay_fund_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_account_id', sa.BigInteger(), nullable=True),
    sa.Column('razorpay_fund_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['vendor_bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['vendor_razorpay_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_razorpay_fund_accounts_bank_account_id'), 'vendor_razorpay_fund_accounts', ['bank_account_id'], unique=True)
    op.create_index(op.f('ix_vendor_razorpay_fund_accounts_contact_id'), 'vendor_razorpay_fund_accounts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_vendor_razorpay_fund_accounts_public_id'), 'vendor_razorpay_fund_accounts', ['public_id'], unique=True)
    op.create_index(op.f('ix_vendor_razorpay_fund_accounts_razorpay_fund_account_id'), 'vendor_razorpay_fund_accounts', ['razorpay_fund_account_id'], unique=True)
    op.drop_index(op.f('ix_vendor_bank_accounts_razorpay_contact_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_razorpay_fund_account_id'), table_name='vendor_bank_accounts')
    op.drop_column('vendor_bank_accounts', 'razorpay_contact_id')
    op.drop_column('vendor_bank_accounts', 'razorpay_fund_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_bank_accounts', sa.Column('razorpay_fund_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('vendor_bank_accounts', sa.Column('razorpay_contact_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vendor_bank_accounts_razorpay_fund_account_id'), 'vendor_bank_accounts', ['razorpay_fund_account_id'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_razorpay_contact_id'), 'vendor_bank_accounts', ['razorpay_contact_id'], unique=False)
    op.drop_index(op.f('ix_vendor_razorpay_fund_accounts_razorpay_fund_account_id'), table_name='vendor_razorpay_fund_accounts')
    op.drop_index(op.f('ix_vendor_razorpay_fund_accounts_public_id'), table_name='vendor_razorpay_fund_accounts')
    op.drop_index(op.f('ix_vendor_razorpay_fund_accounts_contact_id'), table_name='vendor_razorpay_fund_accounts')
    op.drop_index(op.f('ix_vendor_razorpay_fund_accounts_bank_account_id'), table_name='vendor_razorpay_fund_accounts')
    op.drop_table('vendor_razorpay_fund_accounts')
    op.drop_index(op.f('ix_vendor_razorpay_contacts_vendor_id'), table_name='vendor_razorpay_contacts')
    op.drop_index(op.f('ix_vendor_razorpay_contacts_razorpay_contact_id'), table_name='vendor_razorpay_contacts')
    op.drop_index(op.f('ix_vendor_razorpay_contacts_public_id'), table_name='vendor_razorpay_contacts')
    op.drop_table('vendor_razorpay_contacts')
    # ### end Alembic commands ###
