"""add new table room type 

Revision ID: 295dd2b3491b
Revises: 07e687e9cc98
Create Date: 2026-08-11 11:25:41.334224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295dd2b3491b'
down_revision: Union[str, Sequence[str], None] = '07e687e9cc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_room_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'room_type_id', name='uq_property_room_type')
    )
    op.create_index(op.f('ix_property_room_types_property_id'), 'property_room_types', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_room_types_room_type_id'), 'property_room_types', ['room_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_room_types_room_type_id'), table_name='property_room_types')
    op.drop_index(op.f('ix_property_room_types_property_id'), table_name='property_room_types')
    op.drop_table('property_room_types')
    # ### end Alembic commands ###
