"""update table propert room type 

Revision ID: 47fac5f646b3
Revises: 9ae294d57a01
Create Date: 2026-08-13 19:50:30.827079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fac5f646b3'
down_revision: Union[str, Sequence[str], None] = '9ae294d57a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_room_types', sa.Column('public_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_property_room_types_public_id'), 'property_room_types', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_room_types_public_id'), table_name='property_room_types')
    op.drop_column('property_room_types', 'public_id')
    # ### end Alembic commands ###
