"""update property asset table

Revision ID: 4b8786be67a0
Revises: 5327582d2606
Create Date: 2026-08-14 20:09:58.129485

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import Enum as sa_Enum
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8786be67a0'
down_revision: Union[str, Sequence[str], None] = '5327582d2606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    propertyassetusefor_enum = sa_Enum('GALLERY', 'FEATURE', 'COVER', name='propertyassetusefor')
    propertyassetusefor_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the enum type
    op.add_column('property_assets', sa.Column('use_for', propertyassetusefor_enum, nullable=True))
    op.create_index(op.f('ix_property_assets_use_for'), 'property_assets', ['use_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_assets_use_for'), table_name='property_assets')
    op.drop_column('property_assets', 'use_for')
    
    # Drop the enum type
    propertyassetusefor_enum = sa_Enum('GALLERY', 'FEATURE', 'COVER', name='propertyassetusefor')
    propertyassetusefor_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
