"""update city table

Revision ID: 56655892153e
Revises: 4b8786be67a0
Create Date: 2026-08-16 04:11:47.195458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56655892153e'
down_revision: Union[str, Sequence[str], None] = '4b8786be67a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('tag_line', sa.String(length=75), nullable=True))
    op.add_column('cities', sa.Column('short_description', sa.String(length=250), nullable=True))
    op.add_column('cities', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_property_assets_use_for'), table_name='property_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_property_assets_use_for'), 'property_assets', ['use_for'], unique=False)
    op.drop_column('cities', 'is_featured')
    op.drop_column('cities', 'short_description')
    op.drop_column('cities', 'tag_line')
    # ### end Alembic commands ###
