"""add created and updated by add in countries table

Revision ID: 5e1d25a684b5
Revises: 726a802808bc
Create Date: 2026-07-26 21:44:05.813262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1d25a684b5'
down_revision: Union[str, Sequence[str], None] = '726a802808bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('countries', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'countries', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'countries', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.drop_column('countries', 'updated_by')
    op.drop_column('countries', 'created_by')
    # ### end Alembic commands ###
