"""add new tables as database.md

Revision ID: 638ad7af742d
Revises: 56655892153e
Create Date: 2026-08-29 12:04:49.646929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '638ad7af742d'
down_revision: Union[str, Sequence[str], None] = '56655892153e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_policies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('refund_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='cancellationpolicystatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cancellation_policies_public_id'), 'cancellation_policies', ['public_id'], unique=True)
    op.create_index(op.f('ix_cancellation_policies_status'), 'cancellation_policies', ['status'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_payouts_amount'),
    sa.CheckConstraint('period_end >= period_start', name='chk_payouts_period'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payouts_public_id'), 'payouts', ['public_id'], unique=True)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index(op.f('ix_payouts_vendor_id'), 'payouts', ['vendor_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.BigInteger(), nullable=True),
    sa.Column('cancellation_policy_id', sa.BigInteger(), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('num_rooms', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'PARTIALLY_PAID', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_date > check_in_date', name='chk_booking_dates'),
    sa.ForeignKeyConstraint(['cancellation_policy_id'], ['cancellation_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_cancellation_policy_id'), 'bookings', ['cancellation_policy_id'], unique=False)
    op.create_index(op.f('ix_bookings_check_in_date'), 'bookings', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_bookings_check_out_date'), 'bookings', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_bookings_public_id'), 'bookings', ['public_id'], unique=True)
    op.create_index(op.f('ix_bookings_room_type_id'), 'bookings', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('room_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.BigInteger(), nullable=False),
    sa.Column('block_start_date', sa.Date(), nullable=False),
    sa.Column('block_end_date', sa.Date(), nullable=False),
    sa.Column('units_blocked', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('block_end_date > block_start_date', name='chk_room_block_dates'),
    sa.CheckConstraint('units_blocked > 0', name='chk_room_block_units'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_blocks_property_id'), 'room_blocks', ['property_id'], unique=False)
    op.create_index(op.f('ix_room_blocks_public_id'), 'room_blocks', ['public_id'], unique=True)
    op.create_index(op.f('ix_room_blocks_room_type_id'), 'room_blocks', ['room_type_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NETBANKING', 'WALLET', 'CASH', 'BANK_TRANSFER', name='paymentmethod'), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_payment_amount'),
    sa.CheckConstraint('refunded_amount >= 0 AND refunded_amount <= amount', name='chk_payment_refunded_amount'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_public_id'), 'payments', ['public_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('property_room_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_room_type_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_identifier', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='roomunitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_room_type_id'], ['property_room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_room_type_id', 'unit_identifier', name='uq_property_room_unit')
    )
    op.create_index(op.f('ix_property_room_units_property_room_type_id'), 'property_room_units', ['property_room_type_id'], unique=False)
    op.create_index(op.f('ix_property_room_units_public_id'), 'property_room_units', ['public_id'], unique=True)
    op.create_index(op.f('ix_property_room_units_status'), 'property_room_units', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('host_reply', sa.Text(), nullable=True),
    sa.Column('host_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'HIDDEN', 'FLAGGED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_reviews_rating'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_reviews_guest_id'), 'reviews', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reviews_property_id'), 'reviews', ['property_id'], unique=False)
    op.create_index(op.f('ix_reviews_public_id'), 'reviews', ['public_id'], unique=True)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('refund_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED', name='refundrequeststatus'), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_refund_request_amount'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_requests_booking_id'), 'refund_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_payment_id'), 'refund_requests', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_public_id'), 'refund_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_refund_requests_status'), 'refund_requests', ['status'], unique=False)
    op.alter_column('cities', 'tag_line',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('cities', 'short_description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('properties', sa.Column('cancellation_policy_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_properties_cancellation_policy_id'), 'properties', ['cancellation_policy_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'cancellation_policies', ['cancellation_policy_id'], ['id'], ondelete='SET NULL')
    op.add_column('property_room_types', sa.Column('total_units', sa.Integer(), server_default='1', nullable=False))
    op.create_check_constraint('chk_property_room_type_units', 'property_room_types', 'total_units > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_property_room_type_units', 'property_room_types', type_='check')
    op.drop_column('property_room_types', 'total_units')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_cancellation_policy_id'), table_name='properties')
    op.drop_column('properties', 'cancellation_policy_id')
    op.alter_column('cities', 'short_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('cities', 'tag_line',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=75),
               existing_nullable=True)
    op.drop_index(op.f('ix_refund_requests_status'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_public_id'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_payment_id'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_booking_id'), table_name='refund_requests')
    op.drop_table('refund_requests')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_public_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_property_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_guest_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_property_room_units_status'), table_name='property_room_units')
    op.drop_index(op.f('ix_property_room_units_public_id'), table_name='property_room_units')
    op.drop_index(op.f('ix_property_room_units_property_room_type_id'), table_name='property_room_units')
    op.drop_table('property_room_units')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_public_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_room_blocks_room_type_id'), table_name='room_blocks')
    op.drop_index(op.f('ix_room_blocks_public_id'), table_name='room_blocks')
    op.drop_index(op.f('ix_room_blocks_property_id'), table_name='room_blocks')
    op.drop_table('room_blocks')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_type_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_public_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_out_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cancellation_policy_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_payouts_vendor_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_public_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_cancellation_policies_status'), table_name='cancellation_policies')
    op.drop_index(op.f('ix_cancellation_policies_public_id'), table_name='cancellation_policies')
    op.drop_table('cancellation_policies')
    # ### end Alembic commands ###
