"""add created and updated by add in countries, cites, locations table

Revision ID: 726a802808bc
Revises: 74839fd9c341
Create Date: 2026-07-26 21:40:50.184777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726a802808bc'
down_revision: Union[str, Sequence[str], None] = '74839fd9c341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('cities', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'cities', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'cities', 'users', ['updated_by'], ['id'])
    op.add_column('locations', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('locations', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'locations', 'users', ['updated_by'], ['id'])
    op.add_column('users', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'updated_by')
    op.drop_column('locations', 'created_by')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_column('cities', 'updated_by')
    op.drop_column('cities', 'created_by')
    # ### end Alembic commands ###
