"""add property tables

Revision ID: 734f0808e23d
Revises: 3c1f2a4b5d66
Create Date: 2026-08-09 22:23:53.707862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734f0808e23d'
down_revision: Union[str, Sequence[str], None] = '3c1f2a4b5d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('room_type_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sale_per_night', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('HOTEL', 'APARTMENT', 'VILLA', 'RESORT', 'HOSTEL', 'GUEST_HOUSE', 'BED_AND_BREAKFAST', 'COTTAGE', 'CABIN', 'LODGE', 'MOTEL', 'PENSION', 'CHALET', 'FARM_STAY', 'HOUSEBOAT', 'HOME_STAY', name='propertytype'), nullable=True, comment='Type of property, e.g., hotel, apartment, villa, etc.'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='propertystatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'name', name='uq_property_vendor_name'),
    sa.UniqueConstraint('vendor_id', 'slug', name='uq_property_vendor_slug')
    )
    op.create_index(op.f('ix_properties_city_id'), 'properties', ['city_id'], unique=False)
    op.create_index(op.f('ix_properties_location_id'), 'properties', ['location_id'], unique=False)
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_index(op.f('ix_properties_public_id'), 'properties', ['public_id'], unique=True)
    op.create_index(op.f('ix_properties_room_type_id'), 'properties', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_properties_slug'), 'properties', ['slug'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_type'), 'properties', ['type'], unique=False)
    op.create_index(op.f('ix_properties_vendor_id'), 'properties', ['vendor_id'], unique=False)
    op.create_table('property_amenities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('amenity_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'amenity_id', name='uq_property_amenity')
    )
    op.create_index(op.f('ix_property_amenities_amenity_id'), 'property_amenities', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_property_amenities_property_id'), 'property_amenities', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_amenities_public_id'), 'property_amenities', ['public_id'], unique=True)
    op.create_table('property_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='propertyassettype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='propertyassetstatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_assets_asset_type'), 'property_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_property_assets_property_id'), 'property_assets', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_assets_public_id'), 'property_assets', ['public_id'], unique=True)
    op.create_index(op.f('ix_property_assets_status'), 'property_assets', ['status'], unique=False)
    op.create_table('property_facilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'facility_id', name='uq_property_facility')
    )
    op.create_index(op.f('ix_property_facilities_facility_id'), 'property_facilities', ['facility_id'], unique=False)
    op.create_index(op.f('ix_property_facilities_property_id'), 'property_facilities', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_facilities_public_id'), 'property_facilities', ['public_id'], unique=True)
    op.create_table('property_food_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='propertyfoodoptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'name', name='uq_property_food_option_name')
    )
    op.create_index(op.f('ix_property_food_options_name'), 'property_food_options', ['name'], unique=False)
    op.create_index(op.f('ix_property_food_options_property_id'), 'property_food_options', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_food_options_public_id'), 'property_food_options', ['public_id'], unique=True)
    op.create_index(op.f('ix_property_food_options_status'), 'property_food_options', ['status'], unique=False)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_index(op.f('ix_property_food_options_status'), table_name='property_food_options')
    op.drop_index(op.f('ix_property_food_options_public_id'), table_name='property_food_options')
    op.drop_index(op.f('ix_property_food_options_property_id'), table_name='property_food_options')
    op.drop_index(op.f('ix_property_food_options_name'), table_name='property_food_options')
    op.drop_table('property_food_options')
    op.drop_index(op.f('ix_property_facilities_public_id'), table_name='property_facilities')
    op.drop_index(op.f('ix_property_facilities_property_id'), table_name='property_facilities')
    op.drop_index(op.f('ix_property_facilities_facility_id'), table_name='property_facilities')
    op.drop_table('property_facilities')
    op.drop_index(op.f('ix_property_assets_status'), table_name='property_assets')
    op.drop_index(op.f('ix_property_assets_public_id'), table_name='property_assets')
    op.drop_index(op.f('ix_property_assets_property_id'), table_name='property_assets')
    op.drop_index(op.f('ix_property_assets_asset_type'), table_name='property_assets')
    op.drop_table('property_assets')
    op.drop_index(op.f('ix_property_amenities_public_id'), table_name='property_amenities')
    op.drop_index(op.f('ix_property_amenities_property_id'), table_name='property_amenities')
    op.drop_index(op.f('ix_property_amenities_amenity_id'), table_name='property_amenities')
    op.drop_table('property_amenities')
    op.drop_index(op.f('ix_properties_vendor_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug'), table_name='properties')
    op.drop_index(op.f('ix_properties_room_type_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_public_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_location_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
