"""remove user table column

Revision ID: c11590f7cb93
Revises: daef731583c5
Create Date: 2026-07-29 19:09:33.273841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11590f7cb93'
down_revision: Union[str, Sequence[str], None] = 'daef731583c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_updated_by_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_created_by_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_created_by_fkey'), 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('users_updated_by_fkey'), 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###
