"""modify location name unique logic in model

Revision ID: daef731583c5
Revises: 5e1d25a684b5
Create Date: 2026-07-29 13:24:41.386215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daef731583c5'
down_revision: Union[str, Sequence[str], None] = '5e1d25a684b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_unique_constraint('uq_location_city_name', 'locations', ['city_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_location_city_name', 'locations', type_='unique')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    # ### end Alembic commands ###
